[package]
name = "kuska-handshake"
version = "0.1.0"
authors = ["Dhole <dhole@riseup.net>", "Adria Massanet <adria@codecontext.io>"]
edition = "2018"

[lib]
name = "kuska_handshake"

[dependencies]
sodiumoxide = { git = "https://github.com/Dhole/sodiumoxidez", branch = "extra" }
async-std = { version = "1.4.0", features=["unstable","attributes"] }
futures = "0.3.1"
log = "0.4.8"
tokio = { version = "0.2.6", features=["full"] }

[dev-dependencies]
test_utils = { path = "test_utils" }
crossbeam = "0.7.3"
env_logger = "0.7.1"
base64 = "0.11.0"
hex = "0.4.0"

[features]
default = []
sync = []
async_std = []
tokio_compat = [ "async_std" ]

[[example]]
name = "handshake-boxstream-bench"
required-features = ["sync"]

[[example]]
name = "handshake-boxstream"
required-features = ["sync"]

[[example]]
name = "handshake"
required-features = ["sync"]
