
name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: RUSTFLAGS="-D warnings" cargo build --verbose --all-features --all-targets
    - name: Build no features
      run: cargo build --verbose 
    - name: Build sync
      run: cargo build --verbose --features "sync"
    - name: Build async_std
      run: cargo build --verbose --features "async_std"
    - name: Build async_std tokio_compat
      run: cargo build --verbose --features "async_std tokio_compat"
